<?php
namespace app\admin\controller;

use think\Controller;

class Index extends Login
{

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    public function index()
    {
        return $this->fetch('index');
    }
}
