<?php
/**
 * Created by PhpStorm.
 * User: k
 * Date: 2018/11/7
 * Time: 17:57
 */
namespace app\admin\controller;

use think\Controller;
/**
 * Class Shortlinkset
 * @package app\admin\controller
 * 链接检查表
 */
Class Shortlinkset extends Common{

    /**
     * 继承父类自动加载
     */
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * 加载添加link页面
     */
    public function add()
    {
        return $this->view->fetch('add');
    }

    /**
     * 执行添加行为
     */
    public function addAction()
    {

    }
    /**
     * 加载修改页面资源
     */
    public function edit()
    {
        return $this->view->fetch('edit');
    }


    /**
     * 执行修改行为
     */
    public function editAction()
    {

    }
    /**
     * 获取短链列表
     */
    public function getShortlinksetList()
    {

    }

}